name: 'GH Versioniser'
description: 'Updates the Semantic Version of the Repository & tracks the changes.'
inputs:
  # ---------------------------
  # Versioniser Git Credentials
  versioniser-username:
    description: '(Git Credential) Username for the Versioniser that will be displayed in the commit.'
    required: false
    default: 'GitVersioniser'
  versioniser-email:
    description: '(Git Credential) Email for the Versioniser.'
    required: false
    default: 'luzkan.gitversioniser@github.com'
  # ---------------------------
  # (Routine) Versioning
  routine_version:
    description: '(Routine) Routine which will the GitVersioniser follow when versioning your repository.'
    required: false
    default: 'commits_till_last_gitversioniser_commit'
  # ---------------------------
  # (Routine) Contributing
  routine_should_contribute:
    description: '(Routine) When should the GitVersioniser contribute anything to the remote repository.'
    required: false
    default: 'if_build_or_higher'
  routine_commiting:
    description: '(Routine) The way of contributing changes made by GitVersioniser to your repository.'
    required: false
    default: 'push_origin_amend'
  # ---------------------------
  # (Routine) Commit Message
  routine_commit_message:
    description: '(Routine) Decides how the Commit Message made by GitVersioniser will be made.'
    required: false
    default: 'prefix_version_full'
  # ---------------------------
  # (Routine) Tagging
  routine_tagging:
    description: '(Routine) How should GitVersioniser tag your repository.'
    required: false
    default: 'regular'
  routine_prefix_tag_with_v:
    description: '(Routine) When the tag should receive the "v" letter as prefix.'
    required: false
    default: 'always'
  # ---------------------------
  # (Routine) Changelog Handling
  routine_changelog:
    description: '(Routine) Handles the changelog automatically.'
    required: false
    default: 'commit_pattern'
  # ---------------------------
  # (Routine) File Versioning
  routine_file_updater:
    description: '(Routine) Decides how files will be versionised.'
    required: false
    default: 'versionise_files'
  versioned_files:
    description: '(Setting) Decides which files will be versionised.'
    required: false
    default: 'README.md'
outputs:
  time:
    description: 'Example of Returning Variables as Output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    # ---------------------------
    # Versioniser Git Credentials
    - ${{ inputs.versioniser-username }}
    - ${{ inputs.versioniser-email }}
    # ---------------------------
    # Versioning
    - ${{ inputs.routine_version }}
    # ---------------------------
    # Contributing
    - ${{ inputs.routine_should_contribute }}
    - ${{ inputs.routine_commiting }}
    # ---------------------------
    # Commiting Message
    - ${{ inputs.routine_commit_message }}
    # ---------------------------
    # Tagging
    - ${{ inputs.routine_tagging }}
    - ${{ inputs.routine_prefix_tag_with_v }}
    # ---------------------------
    # Changelog Handling
    - ${{ inputs.routine_changelog }}
    # ---------------------------
    # File Versioning
    - ${{ inputs.routine_file_updater }}
    - ${{ inputs.versioned_files }}
