name: 'GH Versioniser'
description: 'Updates the Semantic Version of the Repository & tracks the changes.'
inputs:
  # ---------------------------
  # Versioniser Git Credentials
  versioniser_username:
    description: '(Git Credential) Username for the Versioniser that will be displayed in the commit.'
    required: false
    default: 'GitVersioniser'
  versioniser_email:
    description: '(Git Credential) Email for the Versioniser.'
    required: false
    default: 'luzkan.gitversioniser@github.com'
  # ---------------------------
  # Versioniser Git Credentials
  commit_pattern_increment_tags:
    description: '(Tags) Tags to look for in commit message for semver incrementation.'
    required: false
    default: 'HashtagExplicit'
  commit_pattern_change_tags:
    description: '(Tags) Tags to look for in commit message for changelog entries creation.'
    required: false
    default: 'ClassicChangelog'
  # ---------------------------
  # (Routine) Versioning
  routine_version:
    description: '(Routine) Routine which will the GitVersioniser follow when versioning your repository.'
    required: false
    default: 'VersionTagInCommitsTillLastGitVersioniserCommit'
  # ---------------------------
  # (Routine) Contributing
  routine_should_contribute:
    description: '(Routine) When should the GitVersioniser contribute anything to the remote repository.'
    required: false
    default: 'IfNewVersionIsBuildOrHigher'
  routine_commiting:
    description: '(Routine) The way of contributing changes made by GitVersioniser to your repository.'
    required: false
    default: 'PushOriginAmend'
  # ---------------------------
  # (Routine) Commit Message
  routine_commit_message_describe_changes:
    description: '(Routine) Decides about the descriptive summarization after first commit message line.'
    required: false
    default: 'WithEmoji'
  routine_commit_message_format_version_tag:
    description: '(Routine) Decides the Version Tag string representation.'
    required: false
    default: 'FullButOnlyDigits'
  routine_commit_message_place_version_tag:
    description: '(Routine) Decides the placement of version tag in commit message.'
    required: false
    default: 'Prefix'
  routine_commit_message_summarize_changes:
    description: '(Routine) Decides the summarization of all changes in the first line of commit message.'
    required: false
    default: 'WithEmojiCounted'
  # ---------------------------
  # (Routine) Tagging
  routine_tagging:
    description: '(Routine) How should GitVersioniser tag your repository.'
    required: false
    default: 'regular'
  routine_prefix_tag_with_v:
    description: '(Routine) When the tag should receive the "v" letter as prefix.'
    required: false
    default: 'always'
  # ---------------------------
  # (Routine) Changelog Handling
  routine_changelog:
    description: '(Routine) Handles the changelog automatically.'
    required: false
    default: 'CommitChangeTags'
  # ---------------------------
  # (Routine) File Versioning
  routine_file_updater:
    description: '(Routine) Decides how files will be versionised.'
    required: false
    default: 'VersioniseFiles'
  versioned_files:
    description: '(Setting) Decides which files will be versionised.'
    required: false
    default: 'README.md'
outputs:
  time:
    description: 'Example of Returning Variables as Output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    # ---------------------------
    # Versioniser Git Credentials
    - ${{ inputs.versioniser_username }}
    - ${{ inputs.versioniser_email }}
    # ---------------------------
    # Versioning
    - ${{ inputs.commit_pattern_increment_tags }}
    - ${{ inputs.commit_pattern_change_tags }}
    # ---------------------------
    # Versioning
    - ${{ inputs.routine_version }}
    # ---------------------------
    # Contributing
    - ${{ inputs.routine_should_contribute }}
    - ${{ inputs.routine_commiting }}
    # ---------------------------
    # Commiting Message
    - ${{ inputs.routine_commit_message_describe_changes }}
    - ${{ inputs.routine_commit_message_format_version_tag }}
    - ${{ inputs.routine_commit_message_place_version_tag }}
    - ${{ inputs.routine_commit_message_summarize_changes }}
    # ---------------------------
    # Tagging
    - ${{ inputs.routine_tagging }}
    - ${{ inputs.routine_prefix_tag_with_v }}
    # ---------------------------
    # Changelog Handling
    - ${{ inputs.routine_changelog }}
    # ---------------------------
    # File Versioning
    - ${{ inputs.routine_file_updater }}
    - ${{ inputs.versioned_files }}
