name: GitVersioniser
on:
  workflow_run:
    workflows: ["Linters"]
    branches: [main]
    types:
      - completed
jobs:
  repository_versioning:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Repository Versioning via GitVersioniser
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
        with:
          path: target_repository
          fetch-depth: 0
      - name: Running GitVersioniser
        id: gitversioniser
        uses: luzkan/GitVersioniser@v0
        with:
          # ---------------------------
          # Versioniser Git Credentials
          # ----
          versioniser-username: "GitVersioniser"
          versioniser-email: "luzkan.gitversioniser@github.com"

          # ---------------------------
          # Main
          # ----
          routine_version: "commits_till_last_gitversioniser_commit"
          routine_commiting: "push_main_amend"
          routine_tagging: "always"
          routine_commit_message: "prefix_version_full"

          # ---------------------------
          # Changelog Handling
          # -----
          routine_changelog: "commit_pattern"

          # ---------------------------
          # File Versioning
          # ----
          routine_file_updater: "versionise_files"
          versioned_files: "README.md main.py setup.py arguments.py"
